import type { DemoScenario } from '@/lib/types'
import { daysAgo, daysFromNow, hoursAgo, minutesAgo } from '@/lib/utils/dates'

export const juniorFrontendScenario: DemoScenario = {
  id: 'junior-frontend',
  label: 'Junior Frontend Developer',
  description: 'Алексей, 22 года, Москва — ищет первую работу в продуктовой компании',

  user: {
    id: 'user-jfe',
    name: 'Алексей Петров',
    email: 'aleksey.petrov@gmail.com',
    city: 'Москва',
    onboardingStep: 'complete',
    hhConnected: true,
    planId: 'trial',
    trialEndsAt: daysFromNow(9),
    trialDaysLeft: 9,
    searchGoal: 'Найти работу Junior Frontend разработчика в продуктовой IT-компании',
    experienceYears: 1,
    preferredFormats: ['remote', 'hybrid'],
  },

  hhConnection: {
    status: 'connected',
    lastSyncAt: hoursAgo(2),
    importedResumes: 1,
    importedVacancies: 247,
    email: 'aleksey.petrov@gmail.com',
  },

  resumes: [
    {
      id: 'resume-orig',
      version: 'original',
      title: 'Frontend разработчик',
      summary: 'Начинающий разработчик с опытом в React и JavaScript. Делал несколько учебных проектов.',
      experience: [
        {
          id: 'exp-1',
          company: 'Фриланс',
          position: 'Frontend разработчик',
          period: 'Март 2024 — наст. время',
          description: 'Верстал лендинги и небольшие сайты для клиентов. Использовал HTML, CSS, JavaScript.',
        },
        {
          id: 'exp-2',
          company: 'ООО Веб-Студия «Пиксель»',
          position: 'Стажёр-верстальщик',
          period: 'Июнь 2023 — Февраль 2024 (9 мес.)',
          description: 'Верстал макеты из Figma. Участвовал в поддержке корпоративных сайтов.',
        },
      ],
      skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Git'],
      salaryMin: 80000,
      salaryMax: 110000,
      city: 'Москва',
      format: 'hybrid',
      score: 62,
    },
    {
      id: 'resume-improved',
      version: 'improved',
      title: 'Junior Frontend Developer — React, TypeScript',
      summary: 'Frontend-разработчик с 1 годом коммерческого опыта. Специализируюсь на React и TypeScript. Создал 3 продакшн-проекта с нуля, уменьшил время загрузки сайта на 40% оптимизацией бандла.',
      experience: [
        {
          id: 'exp-1-imp',
          company: 'Фриланс',
          position: 'Frontend Developer',
          period: 'Март 2024 — наст. время',
          description: 'Разработал 6 коммерческих сайтов с нуля на React + Vite. Внедрил TypeScript, увеличил покрытие кода тестами до 70%. Оптимизировал Core Web Vitals: LCP < 1.5s.',
        },
        {
          id: 'exp-2-imp',
          company: 'ООО Веб-Студия «Пиксель»',
          position: 'Frontend Developer (стажировка)',
          period: 'Июнь 2023 — Февраль 2024',
          description: 'Верстал 15+ проектов по макетам Figma. Реализовал компонентную библиотеку на React, сократив время разработки новых страниц на 30%.',
        },
      ],
      skills: ['React', 'TypeScript', 'JavaScript', 'HTML/CSS', 'Git', 'Vite', 'REST API', 'Figma'],
      salaryMin: 90000,
      salaryMax: 130000,
      city: 'Москва',
      format: 'hybrid',
      score: 84,
    },
  ],

  resumeRecommendations: [
    {
      id: 'rec-1',
      section: 'title',
      title: 'Добавьте ключевые технологии в заголовок',
      text: 'Рекрутеры фильтруют по ключевым словам. Добавьте React и TypeScript в заголовок.',
      impact: 'high',
      applied: false,
    },
    {
      id: 'rec-2',
      section: 'summary',
      title: 'Перепишите сводку с конкретными результатами',
      text: 'Замените общие фразы на измеримые достижения: «оптимизировал загрузку на 40%», «сделал X проектов».',
      impact: 'high',
      applied: false,
    },
    {
      id: 'rec-3',
      section: 'experience',
      title: 'Используйте глаголы действия и цифры',
      text: 'Каждый пункт опыта должен начинаться с глагола и содержать результат. Например: «Реализовал → сократил время на 30%».',
      impact: 'medium',
      applied: false,
    },
    {
      id: 'rec-4',
      section: 'skills',
      title: 'Добавьте TypeScript и инструменты сборки',
      text: 'Большинство вакансий требуют TypeScript. Добавьте Vite, webpack или Rollup в навыки.',
      impact: 'medium',
      applied: false,
    },
  ],

  vacancies: [
    {
      id: 'vac-1',
      title: 'Junior Frontend Developer (React)',
      company: 'Технологии Будущего',
      salary: { min: 90000, max: 130000, currency: '₽' },
      matchPercent: 94,
      format: 'remote',
      city: 'Москва',
      tags: ['React', 'TypeScript', 'REST API'],
      collections: ['best_today', 'matches_experience'],
      description: 'Ищем начинающего Frontend-разработчика в продуктовую команду. Стек: React, TypeScript, styled-components. Работа над внутренней SaaS-платформой для B2B-клиентов.',
      matchReasons: ['Опыт с React совпадает', 'Удалённый формат', 'Зарплата в вашем диапазоне', 'Продуктовая компания'],
      missingSkills: ['styled-components'],
      publishedAt: daysAgo(1),
    },
    {
      id: 'vac-2',
      title: 'Frontend разработчик (React/Vue)',
      company: 'DataFlow Analytics',
      salary: { min: 85000, max: 120000, currency: '₽' },
      matchPercent: 88,
      format: 'hybrid',
      city: 'Москва',
      tags: ['React', 'Vue.js', 'JavaScript'],
      collections: ['best_today', 'quick_apply'],
      description: 'Разработка дашборда аналитики на React. Небольшая команда, быстрые итерации, хороший онбординг для джунов.',
      matchReasons: ['Гибридный формат', 'Стек React', 'Дружественный к джунам'],
      missingSkills: ['Vue.js'],
      publishedAt: daysAgo(2),
    },
    {
      id: 'vac-3',
      title: 'Junior React Developer',
      company: 'Маркетплейс ТехТовары',
      salary: { min: 95000, max: 140000, currency: '₽' },
      matchPercent: 86,
      format: 'remote',
      city: 'Москва',
      tags: ['React', 'Redux', 'TypeScript'],
      collections: ['high_salary', 'matches_experience'],
      description: 'Frontend-разработка e-commerce платформы. React + Redux Toolkit, работа с большими объёмами данных.',
      matchReasons: ['Удалённая работа', 'Высокая зарплата', 'React стек'],
      missingSkills: ['Redux Toolkit', 'GraphQL'],
      publishedAt: daysAgo(1),
    },
    {
      id: 'vac-4',
      title: 'Web Developer (Frontend)',
      company: 'AgencyOne',
      salary: { min: 80000, max: 100000, currency: '₽' },
      matchPercent: 79,
      format: 'office',
      city: 'Москва',
      tags: ['HTML', 'CSS', 'JavaScript', 'React'],
      collections: ['quick_apply'],
      description: 'Разработка сайтов и лендингов для клиентов агентства. Быстрый темп работы, разнообразные проекты.',
      matchReasons: ['Стек HTML/CSS/JS', 'Опыт с лендингами'],
      missingSkills: [],
      publishedAt: daysAgo(3),
    },
    {
      id: 'vac-5',
      title: 'Junior Frontend (Next.js)',
      company: 'FinTech Lab',
      salary: { min: 100000, max: 150000, currency: '₽' },
      matchPercent: 76,
      format: 'hybrid',
      city: 'Москва',
      tags: ['Next.js', 'React', 'TypeScript'],
      collections: ['high_salary'],
      description: 'Разработка финтех-продуктов на Next.js. Команда 8 человек, код ревью, парное программирование.',
      matchReasons: ['Хорошая зарплата', 'React знаком'],
      missingSkills: ['Next.js', 'тестирование (Jest)'],
      publishedAt: daysAgo(4),
    },
    {
      id: 'vac-6',
      title: 'Frontend Developer (стартап)',
      company: 'GreenTech Startup',
      salary: { min: 85000, max: 115000, currency: '₽' },
      matchPercent: 73,
      format: 'remote',
      city: 'Москва',
      tags: ['React', 'Node.js'],
      collections: ['quick_apply'],
      description: 'Стартап в EdTech. Ищем разработчика, готового расти вместе с продуктом.',
      matchReasons: ['Удалённая работа', 'React'],
      missingSkills: ['Node.js основы'],
      publishedAt: daysAgo(2),
    },
    {
      id: 'vac-7',
      title: 'Junior Frontend Developer',
      company: 'СберТех',
      salary: { min: 100000, max: 145000, currency: '₽' },
      matchPercent: 81,
      format: 'hybrid',
      city: 'Москва',
      tags: ['React', 'TypeScript', 'Git'],
      collections: ['high_salary', 'matches_experience'],
      description: 'Крупнейший банк России. Стабильность, ДМС, карьерный рост.',
      matchReasons: ['Большая зарплата', 'React стек', 'Гибридный формат'],
      missingSkills: ['Angular (базово)'],
      publishedAt: daysAgo(1),
    },
    {
      id: 'vac-8',
      title: 'React Developer (удалёнка)',
      company: 'Яндекс Практикум',
      salary: { min: 110000, max: 160000, currency: '₽' },
      matchPercent: 77,
      format: 'remote',
      city: 'Москва',
      tags: ['React', 'TypeScript', 'Jest'],
      collections: ['high_salary', 'best_today'],
      description: 'EdTech-платформа для обучения разработчиков. Работа над интерактивными тренажёрами.',
      matchReasons: ['Полностью удалённо', 'Высокая зарплата', 'React + TypeScript'],
      missingSkills: ['Jest (базово)', 'Storybook'],
      publishedAt: daysAgo(1),
    },
    {
      id: 'vac-9',
      title: 'Frontend Developer (стажировка→оффер)',
      company: 'Авито',
      salary: { min: 90000, max: 120000, currency: '₽' },
      matchPercent: 85,
      format: 'hybrid',
      city: 'Москва',
      tags: ['React', 'TypeScript', 'CSS'],
      collections: ['best_today', 'quick_apply'],
      description: 'Программа стажировки с конвертацией в постоянную позицию. Менторство, ревью кода.',
      matchReasons: ['Программа для джунов', 'React стек', 'Менторство'],
      missingSkills: ['Алгоритмы (средний)'],
      publishedAt: daysAgo(2),
    },
    {
      id: 'vac-10',
      title: 'Frontend Developer (Remote)',
      company: 'Skyeng',
      salary: { min: 95000, max: 130000, currency: '₽' },
      matchPercent: 79,
      format: 'remote',
      city: 'Москва',
      tags: ['React', 'JavaScript', 'CSS'],
      collections: ['quick_apply', 'matches_experience'],
      description: 'EdTech-сервис для изучения английского. Распределённая команда, гибкий график.',
      matchReasons: ['Полностью удалённо', 'Гибкий график', 'React стек'],
      missingSkills: [],
      publishedAt: daysAgo(3),
    },
    {
      id: 'vac-11',
      title: 'Junior React Developer',
      company: 'MTS Digital',
      salary: { min: 105000, max: 145000, currency: '₽' },
      matchPercent: 83,
      format: 'hybrid',
      city: 'Москва',
      tags: ['React', 'TypeScript', 'Redux'],
      collections: ['high_salary', 'best_today'],
      description: 'IT-подразделение МТС. Разработка мобильного приложения и веб-порталов.',
      matchReasons: ['Высокая зарплата', 'Крупная компания', 'React + TypeScript'],
      missingSkills: ['Redux Toolkit'],
      publishedAt: hoursAgo(18),
    },
    {
      id: 'vac-12',
      title: 'Frontend Engineer',
      company: 'Тинькофф',
      salary: { min: 120000, max: 170000, currency: '₽' },
      matchPercent: 71,
      format: 'hybrid',
      city: 'Москва',
      tags: ['React', 'TypeScript', 'GraphQL'],
      collections: ['high_salary'],
      description: 'Финтех-лидер. Разработка интерфейсов для банковских продуктов.',
      matchReasons: ['Топовая зарплата', 'React стек'],
      missingSkills: ['GraphQL', 'Опыт в финтехе'],
      publishedAt: daysAgo(4),
    },
  ],

  applications: [
    {
      id: 'app-1',
      vacancyId: 'vac-1',
      vacancyTitle: 'Junior Frontend Developer (React)',
      company: 'Технологии Будущего',
      status: 'interview',
      sentAt: daysAgo(5),
      coverLetter: 'Здравствуйте! Меня привлекает позиция Junior Frontend Developer в вашей компании. Я работаю с React уже год, успел создать несколько коммерческих проектов с TypeScript. Особенно интересна работа над B2B SaaS-платформой — это именно тот опыт, который я хочу получить. Готов учиться и вносить вклад с первых дней.',
      source: 'auto',
      statusHistory: [
        { status: 'sent', at: daysAgo(5) },
        { status: 'viewed', at: daysAgo(4) },
        { status: 'replied', at: daysAgo(3) },
        { status: 'interview', at: daysAgo(1) },
      ],
    },
    {
      id: 'app-2',
      vacancyId: 'vac-2',
      vacancyTitle: 'Frontend разработчик (React/Vue)',
      company: 'DataFlow Analytics',
      status: 'replied',
      sentAt: daysAgo(7),
      coverLetter: 'Добрый день! Заинтересовался вакансией Frontend-разработчика. У меня есть опыт с React, знаком с концепцией дашбордов аналитики. Хочу развиваться в направлении data-driven интерфейсов.',
      source: 'auto',
      statusHistory: [
        { status: 'sent', at: daysAgo(7) },
        { status: 'viewed', at: daysAgo(6) },
        { status: 'replied', at: daysAgo(2) },
      ],
    },
    {
      id: 'app-3',
      vacancyId: 'vac-3',
      vacancyTitle: 'Junior React Developer',
      company: 'Маркетплейс ТехТовары',
      status: 'viewed',
      sentAt: daysAgo(4),
      coverLetter: 'Здравствуйте! Меня привлекает возможность работать над e-commerce платформой. Понимаю специфику высоконагруженных систем, готов изучить Redux Toolkit.',
      source: 'auto',
      statusHistory: [
        { status: 'sent', at: daysAgo(4) },
        { status: 'viewed', at: daysAgo(2) },
      ],
    },
    {
      id: 'app-4',
      vacancyId: 'vac-4',
      vacancyTitle: 'Web Developer (Frontend)',
      company: 'AgencyOne',
      status: 'sent',
      sentAt: daysAgo(2),
      coverLetter: 'Добрый день! Откликаюсь на позицию Web Developer. У меня есть практический опыт верстки лендингов и работы с React.',
      source: 'auto',
      statusHistory: [
        { status: 'sent', at: daysAgo(2) },
      ],
    },
    {
      id: 'app-5',
      vacancyId: 'vac-5',
      vacancyTitle: 'Junior Frontend (Next.js)',
      company: 'FinTech Lab',
      status: 'planned',
      scheduledFor: daysFromNow(0),
      coverLetter: 'Здравствуйте! Очень интересна позиция в FinTech Lab. Next.js изучаю самостоятельно, базовый уровень уже есть. Понимаю специфику финтех-продуктов и готов разобраться в домене быстро.',
      source: 'auto',
      statusHistory: [],
    },
    {
      id: 'app-6',
      vacancyId: 'vac-6',
      vacancyTitle: 'Frontend Developer (стартап)',
      company: 'GreenTech Startup',
      status: 'planned',
      scheduledFor: daysFromNow(0),
      coverLetter: 'Привет команда GreenTech! Заинтересован в позиции — EdTech-направление мне особенно близко. Готов расти вместе с продуктом и брать на себя ответственность с первых дней.',
      source: 'auto',
      statusHistory: [],
    },
    {
      id: 'app-8',
      vacancyId: 'vac-7',
      vacancyTitle: 'Junior Frontend Developer',
      company: 'СберТех',
      status: 'planned',
      scheduledFor: daysFromNow(0),
      coverLetter: 'Добрый день! Хочу присоединиться к команде СберТех. Работаю с React и TypeScript, имею опыт разработки коммерческих проектов. Привлекает стабильность и возможность работать над масштабными продуктами.',
      source: 'auto',
      statusHistory: [],
    },
    {
      id: 'app-9',
      vacancyId: 'vac-8',
      vacancyTitle: 'React Developer (удалёнка)',
      company: 'Яндекс Практикум',
      status: 'planned',
      scheduledFor: daysFromNow(0),
      coverLetter: 'Здравствуйте! Яндекс Практикум — продукт, которым я пользовался сам. Хотел бы участвовать в создании инструментов обучения, которые помогают тысячам разработчиков. Мой стек — React, TypeScript, хорошее понимание UI/UX.',
      source: 'auto',
      statusHistory: [],
    },
    {
      id: 'app-10',
      vacancyId: 'vac-9',
      vacancyTitle: 'Frontend Developer (стажировка→оффер)',
      company: 'Авито',
      status: 'planned',
      scheduledFor: daysFromNow(0),
      coverLetter: 'Добрый день! Авито — одна из самых интересных продуктовых компаний в России. Программа стажировки с ментором — отличная возможность для старта карьеры. Готов усердно учиться и быстро расти.',
      source: 'auto',
      statusHistory: [],
    },
    {
      id: 'app-11',
      vacancyId: 'vac-10',
      vacancyTitle: 'Frontend Developer (Remote)',
      company: 'Skyeng',
      status: 'planned',
      scheduledFor: daysFromNow(0),
      coverLetter: 'Привет! Skyeng — лидер EdTech в России. Удалённый формат и гибкий график позволят мне сосредоточиться на результате. Имею опыт с React и умею организовать асинхронную работу.',
      source: 'auto',
      statusHistory: [],
    },
    {
      id: 'app-12',
      vacancyId: 'vac-11',
      vacancyTitle: 'Junior React Developer',
      company: 'MTS Digital',
      status: 'planned',
      scheduledFor: daysFromNow(0),
      coverLetter: 'Добрый день! Хочу попробовать себя в крупном IT-подразделении. MTS Digital — масштабные продукты и сильная инженерная культура. Готов изучить Redux Toolkit в первые недели работы.',
      source: 'auto',
      statusHistory: [],
    },
    {
      id: 'app-7',
      vacancyId: 'vac-2',
      vacancyTitle: 'Product Manager Intern',
      company: 'OldTech Corp',
      status: 'rejected',
      sentAt: daysAgo(14),
      coverLetter: '',
      source: 'auto',
      skipReason: 'Не соответствует профилю',
      statusHistory: [
        { status: 'sent', at: daysAgo(14) },
        { status: 'rejected', at: daysAgo(10) },
      ],
    },
  ],

  threads: [
    {
      id: 'thread-1',
      vacancyId: 'vac-1',
      vacancyTitle: 'Junior Frontend Developer (React)',
      company: 'Технологии Будущего',
      recruiterName: 'Мария Соколова',
      messages: [
        {
          id: 'msg-1-1',
          threadId: 'thread-1',
          from: 'recruiter',
          text: 'Добрый день, Алексей! Мы рассмотрели ваше резюме и хотим пригласить вас на техническое собеседование. У вас интересный опыт с React-проектами. Когда вам удобно созвониться?',
          sentAt: daysAgo(3),
          read: true,
        },
        {
          id: 'msg-1-2',
          threadId: 'thread-1',
          from: 'user',
          text: 'Добрый день, Мария! Спасибо за приглашение! Мне удобно в любой день на следующей неделе после 12:00.',
          sentAt: daysAgo(3),
          read: true,
        },
        {
          id: 'msg-1-3',
          threadId: 'thread-1',
          from: 'recruiter',
          text: 'Отлично! Тогда предлагаю в среду в 14:00. Встреча пройдёт в Zoom, длительность около 1 часа. Вышлю ссылку накануне.',
          sentAt: daysAgo(2),
          read: true,
        },
        {
          id: 'msg-1-4',
          threadId: 'thread-1',
          from: 'recruiter',
          text: 'Алексей, напоминаю — встреча завтра в 14:00. Ссылка: zoom.us/j/demo123. Удачи! 👋',
          sentAt: hoursAgo(20),
          read: false,
        },
      ],
      pinned: true,
      unreadCount: 1,
      lastMessageAt: hoursAgo(20),
    },
    {
      id: 'thread-2',
      vacancyId: 'vac-2',
      vacancyTitle: 'Frontend разработчик (React/Vue)',
      company: 'DataFlow Analytics',
      recruiterName: 'Игорь Романов',
      messages: [
        {
          id: 'msg-2-1',
          threadId: 'thread-2',
          from: 'recruiter',
          text: 'Привет! Видел ваш отклик на позицию Frontend-разработчика. Нам интересен ваш опыт. Можете рассказать подробнее о проектах, где использовали React?',
          sentAt: daysAgo(2),
          read: false,
        },
      ],
      pinned: false,
      unreadCount: 1,
      lastMessageAt: daysAgo(2),
    },
    {
      id: 'thread-3',
      vacancyId: 'vac-7',
      vacancyTitle: 'Junior Frontend Developer',
      company: 'СберТех',
      recruiterName: 'Наталья Козлова',
      messages: [
        {
          id: 'msg-3-1',
          threadId: 'thread-3',
          from: 'recruiter',
          text: 'Здравствуйте, Алексей. К сожалению, мы приняли решение продолжить с другими кандидатами. Спасибо за интерес к нашей компании и желаем успехов в поиске.',
          sentAt: daysAgo(4),
          read: true,
        },
      ],
      pinned: false,
      unreadCount: 0,
      lastMessageAt: daysAgo(4),
    },
    {
      id: 'thread-4',
      vacancyId: 'vac-8',
      vacancyTitle: 'React Developer (удалёнка)',
      company: 'Яндекс Практикум',
      recruiterName: 'Дмитрий Волков',
      messages: [
        {
          id: 'msg-4-1',
          threadId: 'thread-4',
          from: 'recruiter',
          text: 'Добрый день! Мы рассмотрели ваш отклик и хотели бы пообщаться. Вы можете выйти на звонок на этой неделе?',
          sentAt: daysAgo(1),
          read: false,
        },
      ],
      pinned: false,
      unreadCount: 1,
      lastMessageAt: daysAgo(1),
    },
    {
      id: 'thread-5',
      vacancyId: 'vac-9',
      vacancyTitle: 'Frontend Developer (стажировка→оффер)',
      company: 'Авито',
      recruiterName: 'Елена Петрова',
      messages: [
        {
          id: 'msg-5-1',
          threadId: 'thread-5',
          from: 'recruiter',
          text: 'Алексей, добрый день! Посмотрела ваше резюме — интересный опыт. У нас есть стажировка с конвертацией в оффер. Вы проходили курсы по алгоритмам?',
          sentAt: daysAgo(3),
          read: true,
        },
        {
          id: 'msg-5-2',
          threadId: 'thread-5',
          from: 'user',
          text: 'Добрый день, Елена! Да, прошёл курс по алгоритмам. Готов пройти техническое задание.',
          sentAt: daysAgo(3),
          read: true,
        },
        {
          id: 'msg-5-3',
          threadId: 'thread-5',
          from: 'recruiter',
          text: 'Отлично! Вышлю ссылку на тестовое сегодня вечером. Срок — 3 дня.',
          sentAt: daysAgo(2),
          read: false,
        },
      ],
      pinned: false,
      unreadCount: 1,
      lastMessageAt: daysAgo(2),
    },
    {
      id: 'thread-6',
      vacancyId: 'vac-10',
      vacancyTitle: 'Frontend Developer (Remote)',
      company: 'Skyeng',
      recruiterName: 'Ксения Иванова',
      messages: [
        {
          id: 'msg-6-1',
          threadId: 'thread-6',
          from: 'recruiter',
          text: 'Привет! Увидела ваш отклик. У нас полностью удалённая команда, офиса нет. Вам это подходит?',
          sentAt: daysAgo(5),
          read: true,
        },
        {
          id: 'msg-6-2',
          threadId: 'thread-6',
          from: 'user',
          text: 'Да, удалённый формат мне подходит полностью.',
          sentAt: daysAgo(5),
          read: true,
        },
        {
          id: 'msg-6-3',
          threadId: 'thread-6',
          from: 'recruiter',
          text: 'Супер! Тогда отправлю анкету для заполнения. Это займёт 10 минут.',
          sentAt: daysAgo(4),
          read: true,
        },
      ],
      pinned: false,
      unreadCount: 0,
      lastMessageAt: daysAgo(4),
    },
    {
      id: 'thread-7',
      vacancyId: 'vac-11',
      vacancyTitle: 'Junior React Developer',
      company: 'MTS Digital',
      recruiterName: 'Антон Смирнов',
      messages: [
        {
          id: 'msg-7-1',
          threadId: 'thread-7',
          from: 'recruiter',
          text: 'Алексей, добрый день! Мы рассмотрели ваше резюме и хотим сделать оффер. Можем обсудить детали?',
          sentAt: hoursAgo(3),
          read: false,
        },
      ],
      pinned: false,
      unreadCount: 1,
      lastMessageAt: hoursAgo(3),
    },
    {
      id: 'thread-8',
      vacancyId: 'vac-12',
      vacancyTitle: 'Frontend Engineer',
      company: 'Тинькофф',
      recruiterName: 'Анна Белова',
      messages: [
        {
          id: 'msg-8-1',
          threadId: 'thread-8',
          from: 'recruiter',
          text: 'Добрый день! Нас заинтересовало ваше резюме. Можете показать портфолио или ссылку на GitHub?',
          sentAt: daysAgo(6),
          read: true,
        },
        {
          id: 'msg-8-2',
          threadId: 'thread-8',
          from: 'user',
          text: 'Конечно, вот ссылка на мои проекты: github.com/aleksey-petrov',
          sentAt: daysAgo(6),
          read: true,
        },
        {
          id: 'msg-8-3',
          threadId: 'thread-8',
          from: 'recruiter',
          text: 'Посмотрела — выглядит интересно. Давайте назначим короткий скрининг-звонок на 20 минут?',
          sentAt: daysAgo(5),
          read: true,
        },
      ],
      pinned: false,
      unreadCount: 0,
      lastMessageAt: daysAgo(5),
    },
  ],

  interviews: [
    {
      id: 'int-1',
      vacancyId: 'vac-1',
      vacancyTitle: 'Junior Frontend Developer (React)',
      company: 'Технологии Будущего',
      stage: 'hr',
      scheduledAt: daysFromNow(1),
      durationMinutes: 60,
      format: 'video',
      meetingLink: 'https://zoom.us/j/demo123',
      status: 'upcoming',
      interviewers: ['Мария Соколова (HR)'],
      prepPackage: {
        companyInfo: 'Технологии Будущего — российская IT-компания, основана в 2018 году. Разрабатывает B2B SaaS-платформу для автоматизации операций в среднем бизнесе. Команда 120 человек, 40 из них в разработке. Финансируется от Series A. Клиенты в 15 отраслях.',
        companyValues: ['Прозрачность', 'Постоянное обучение', 'Ответственность за результат'],
        likelyQuestions: [
          {
            id: 'q-1',
            question: 'Расскажите о себе и своём пути в разработку',
            hint: 'Кратко: образование → первые проекты → коммерческий опыт → почему именно frontend',
          },
          {
            id: 'q-2',
            question: 'Почему именно наша компания?',
            hint: 'Упомяните B2B SaaS-специфику, интерес к продуктовой разработке',
          },
          {
            id: 'q-3',
            question: 'Какой ваш самый интересный React-проект?',
            hint: 'Подготовьте 1-2 конкретных проекта: задача, решение, результат',
          },
          {
            id: 'q-4',
            question: 'Как вы учитесь новым технологиям?',
            hint: 'Расскажите о конкретных ресурсах: документация, практика, код-ревью',
          },
        ],
        checklist: [
          { id: 'ch-1', text: 'Изучить сайт компании и продукт', done: false },
          { id: 'ch-2', text: 'Подготовить рассказ о себе (2 минуты)', done: false },
          { id: 'ch-3', text: 'Вспомнить детали 2-3 React-проектов', done: false },
          { id: 'ch-4', text: 'Проверить Zoom и интернет-соединение', done: false },
          { id: 'ch-5', text: 'Приготовить вопросы для рекрутера', done: false },
        ],
        tips: [
          'Будьте конкретны — приводите примеры из реальных проектов',
          'Покажите готовность учиться — в джун-позициях это важнее всего',
          'Не бойтесь сказать "не знаю, но разберусь вот так"',
        ],
      },
    },
  ],

  notifications: [
    {
      id: 'notif-1',
      type: 'interview_scheduled',
      title: 'Назначено интервью',
      body: 'Технологии Будущего пригласили вас на HR-интервью на завтра в 14:00',
      relatedEntityId: 'int-1',
      relatedEntityType: 'interview',
      createdAt: daysAgo(2),
      read: false,
    },
    {
      id: 'notif-2',
      type: 'recruiter_reply',
      title: 'Новое сообщение от рекрутера',
      body: 'DataFlow Analytics: «Привет! Видел ваш отклик...»',
      relatedEntityId: 'thread-2',
      relatedEntityType: 'thread',
      createdAt: daysAgo(2),
      read: false,
    },
    {
      id: 'notif-3',
      type: 'apply_sent',
      title: 'Отклик отправлен',
      body: 'AI отправил отклик в AgencyOne на Web Developer (Frontend)',
      relatedEntityId: 'app-4',
      relatedEntityType: 'application',
      createdAt: daysAgo(2),
      read: true,
    },
    {
      id: 'notif-4',
      type: 'application_viewed',
      title: 'Отклик просмотрен',
      body: 'Маркетплейс ТехТовары просмотрели ваш отклик',
      relatedEntityId: 'app-3',
      relatedEntityType: 'application',
      createdAt: daysAgo(2),
      read: true,
    },
    {
      id: 'notif-5',
      type: 'hh_connected',
      title: 'HeadHunter подключён',
      body: 'Импортировано 1 резюме и найдено 247 вакансий',
      createdAt: daysAgo(8),
      read: true,
    },
    {
      id: 'notif-6',
      type: 'trial_expiring',
      title: 'Пробный период заканчивается',
      body: 'До конца пробного периода осталось 9 дней. Не прерывайте поиск!',
      createdAt: daysAgo(1),
      read: false,
    },
  ],

  eventSchedule: [
    {
      id: 'evt-1',
      triggerType: 'timer',
      triggerAfterMs: 12000,
      eventType: 'new_message',
      payload: {
        threadId: 'thread-2',
        message: {
          id: 'msg-2-2',
          from: 'recruiter',
          text: 'Кстати, у нас в офисе отличный кофе и митапы каждый четверг 😄 Будем рады познакомиться!',
        },
      },
      fired: false,
    },
    {
      id: 'evt-2',
      triggerType: 'action',
      triggerOnAction: 'resume_improved',
      eventType: 'vacancy_found',
      payload: {
        count: 3,
        topVacancy: { title: 'React Developer', company: 'NovaTech', matchPercent: 91 },
      },
      fired: false,
    },
  ],
}
