import type { DemoScenario } from '@/lib/types'
import { daysAgo, daysFromNow, hoursAgo } from '@/lib/utils/dates'

export const productAnalystScenario: DemoScenario = {
  id: 'product-analyst',
  label: 'Product Analyst',
  description: 'Дарья, 27 лет, Санкт-Петербург — ищет рост в product-аналитике',

  user: {
    id: 'user-pa',
    name: 'Дарья Иванова',
    email: 'dasha.ivanova@yandex.ru',
    city: 'Санкт-Петербург',
    onboardingStep: 'complete',
    hhConnected: true,
    planId: 'trial',
    trialEndsAt: daysFromNow(7),
    trialDaysLeft: 7,
    searchGoal: 'Вырасти до Middle Product Analyst в tech-компании',
    experienceYears: 3,
    preferredFormats: ['hybrid', 'remote'],
  },

  hhConnection: {
    status: 'connected',
    lastSyncAt: hoursAgo(5),
    importedResumes: 2,
    importedVacancies: 184,
    email: 'dasha.ivanova@yandex.ru',
  },

  resumes: [
    {
      id: 'resume-orig-pa',
      version: 'original',
      title: 'Аналитик данных',
      summary: 'Аналитик с 3 годами опыта. Работаю с данными, делаю отчёты, умею SQL.',
      experience: [
        {
          id: 'exp-pa-1',
          company: 'СберТех',
          position: 'Аналитик',
          period: 'Январь 2022 — наст. время',
          description: 'Анализ данных, построение отчётов в BI-системе, работа с SQL.',
        },
        {
          id: 'exp-pa-2',
          company: 'ООО Ромашка',
          position: 'Аналитик-стажёр',
          period: 'Июнь 2021 — Декабрь 2021',
          description: 'Помогала с составлением аналитических отчётов.',
        },
      ],
      skills: ['SQL', 'Excel', 'Tableau', 'Python'],
      salaryMin: 120000,
      salaryMax: 160000,
      city: 'Санкт-Петербург',
      format: 'hybrid',
      score: 67,
    },
    {
      id: 'resume-improved-pa',
      version: 'improved',
      title: 'Product Analyst — SQL, Python, A/B тесты',
      summary: 'Product Analyst с 3 годами опыта в технологических компаниях. Провела 40+ A/B тестов, увеличила retention на 18%. Владею полным стеком продуктовой аналитики: от сбора гипотез до интерпретации результатов.',
      experience: [
        {
          id: 'exp-pa-1-imp',
          company: 'СберТех',
          position: 'Product Analyst',
          period: 'Январь 2022 — наст. время',
          description: 'Провела 40+ A/B тестов для улучшения конверсии. Построила систему метрик (North Star + дерево метрик). Увеличила retention D7 на 18% через оптимизацию онбординга.',
        },
        {
          id: 'exp-pa-2-imp',
          company: 'ООО Ромашка',
          position: 'Junior Analyst',
          period: 'Июнь 2021 — Декабрь 2021',
          description: 'Разработала автоматизированный пайплайн отчётности на Python+SQL, сократив время подготовки отчётов на 60%.',
        },
      ],
      skills: ['SQL', 'Python', 'Tableau', 'A/B тесты', 'Amplitude', 'Excel', 'Jupyter'],
      salaryMin: 140000,
      salaryMax: 200000,
      city: 'Санкт-Петербург',
      format: 'hybrid',
      score: 89,
    },
  ],

  resumeRecommendations: [
    {
      id: 'rec-pa-1',
      section: 'title',
      title: 'Уточните специализацию в заголовке',
      text: 'Замените «Аналитик данных» на «Product Analyst». Добавьте ключевые инструменты.',
      impact: 'high',
      applied: false,
    },
    {
      id: 'rec-pa-2',
      section: 'summary',
      title: 'Добавьте результаты A/B тестов',
      text: 'Product Analyst без A/B тестов в резюме воспринимается как data analyst. Добавьте конкретику.',
      impact: 'high',
      applied: false,
    },
    {
      id: 'rec-pa-3',
      section: 'skills',
      title: 'Добавьте инструменты продуктовой аналитики',
      text: 'Amplitude, Mixpanel или метрики-фреймворки важны для product-позиций.',
      impact: 'medium',
      applied: false,
    },
  ],

  vacancies: [
    {
      id: 'vac-pa-1',
      title: 'Middle Product Analyst',
      company: 'Авито Технологии',
      salary: { min: 160000, max: 220000, currency: '₽' },
      matchPercent: 91,
      format: 'hybrid',
      city: 'Санкт-Петербург',
      tags: ['SQL', 'Python', 'A/B тесты', 'Amplitude'],
      collections: ['best_today', 'matches_experience', 'high_salary'],
      description: 'Ищем аналитика для развития направления поиска. Полный цикл: гипотезы, A/B, интерпретация, принятие решений совместно с продактом.',
      matchReasons: ['Опыт A/B тестов', 'Стек SQL+Python', 'Hybrid формат', 'Рост до Middle'],
      missingSkills: ['Amplitude (базовый уровень приветствуется)'],
      publishedAt: daysAgo(1),
    },
    {
      id: 'vac-pa-2',
      title: 'Product Analyst (фин-тех)',
      company: 'Тинькофф',
      salary: { min: 180000, max: 250000, currency: '₽' },
      matchPercent: 84,
      format: 'hybrid',
      city: 'Санкт-Петербург',
      tags: ['SQL', 'Python', 'ClickHouse'],
      collections: ['high_salary', 'best_today'],
      description: 'Аналитик в команду развития кредитных продуктов. Большие объёмы данных, ClickHouse, Tableau.',
      matchReasons: ['SQL эксперт', 'Tableau знаком', 'Отличная зарплата'],
      missingSkills: ['ClickHouse'],
      publishedAt: daysAgo(2),
    },
    {
      id: 'vac-pa-3',
      title: 'Аналитик продуктов',
      company: 'Lamoda',
      salary: { min: 140000, max: 180000, currency: '₽' },
      matchPercent: 79,
      format: 'remote',
      city: 'Санкт-Петербург',
      tags: ['SQL', 'Excel', 'Tableau'],
      collections: ['quick_apply', 'matches_experience'],
      description: 'Lamoda ищет аналитика для команды CRM. Работа с клиентскими сегментами и RFM-анализом.',
      matchReasons: ['Удалённо', 'Стек подходит', 'FMCG опыт будет плюсом'],
      missingSkills: [],
      publishedAt: daysAgo(3),
    },
  ],

  applications: [
    {
      id: 'app-pa-1',
      vacancyId: 'vac-pa-1',
      vacancyTitle: 'Middle Product Analyst',
      company: 'Авито Технологии',
      status: 'replied',
      sentAt: daysAgo(4),
      coverLetter: 'Добрый день! Меня очень привлекает позиция Product Analyst в Авито. За 3 года опыта провела 40+ A/B тестов, глубоко понимаю цикл работы с гипотезами.',
      source: 'auto',
      statusHistory: [
        { status: 'sent', at: daysAgo(4) },
        { status: 'viewed', at: daysAgo(3) },
        { status: 'replied', at: daysAgo(1) },
      ],
    },
    {
      id: 'app-pa-2',
      vacancyId: 'vac-pa-2',
      vacancyTitle: 'Product Analyst (фин-тех)',
      company: 'Тинькофф',
      status: 'sent',
      sentAt: daysAgo(3),
      coverLetter: 'Добрый день! Привлекает масштаб данных в Тинькофф. Готова быстро освоить ClickHouse, SQL знаю глубоко.',
      source: 'auto',
      statusHistory: [
        { status: 'sent', at: daysAgo(3) },
      ],
    },
    {
      id: 'app-pa-3',
      vacancyId: 'vac-pa-3',
      vacancyTitle: 'Аналитик продуктов',
      company: 'Lamoda',
      status: 'planned',
      scheduledFor: daysFromNow(0),
      coverLetter: 'Здравствуйте! Интересна работа в Lamoda с клиентской аналитикой.',
      source: 'auto',
      statusHistory: [],
    },
  ],

  threads: [
    {
      id: 'thread-pa-1',
      vacancyId: 'vac-pa-1',
      vacancyTitle: 'Middle Product Analyst',
      company: 'Авито Технологии',
      recruiterName: 'Елена Кузнецова',
      messages: [
        {
          id: 'msg-pa-1-1',
          threadId: 'thread-pa-1',
          from: 'recruiter',
          text: 'Дарья, добрый день! Вы подходите нам по опыту. Хотели бы пригласить вас на первый звонок с командой аналитики. 30 минут, можно в любой день недели?',
          sentAt: daysAgo(1),
          read: false,
        },
      ],
      pinned: false,
      unreadCount: 1,
      lastMessageAt: daysAgo(1),
    },
  ],

  interviews: [
    {
      id: 'int-pa-1',
      vacancyId: 'vac-pa-1',
      vacancyTitle: 'Middle Product Analyst',
      company: 'Авито Технологии',
      stage: 'hr',
      scheduledAt: daysFromNow(3),
      durationMinutes: 45,
      format: 'video',
      meetingLink: 'https://meet.google.com/demo-avito',
      status: 'upcoming',
      interviewers: ['Елена Кузнецова (HR)', 'Павел Орлов (Lead Analyst)'],
      prepPackage: {
        companyInfo: 'Авито — крупнейшая российская доска объявлений. 50+ млн пользователей, сотни аналитиков. Data-driven культура: решения принимаются на основе данных на всех уровнях.',
        companyValues: ['Data-driven decisions', 'Ownership', 'Скорость итераций'],
        likelyQuestions: [
          {
            id: 'q-pa-1',
            question: 'Опишите A/B тест, которым гордитесь',
            hint: 'Гипотеза → дизайн эксперимента → результаты → решение',
          },
          {
            id: 'q-pa-2',
            question: 'Как бы вы измерили успех функции поиска?',
            hint: 'North Star метрика + 3-5 подметрик, расскажите о компромиссах',
          },
          {
            id: 'q-pa-3',
            question: 'Расскажите о конфликте с продактом из-за интерпретации данных',
            hint: 'Покажите зрелость: умение аргументировать позицию данными',
          },
        ],
        checklist: [
          { id: 'ch-pa-1', text: 'Изучить продукт Авито — попробовать как пользователь', done: false },
          { id: 'ch-pa-2', text: 'Подготовить кейс с A/B тестом', done: false },
          { id: 'ch-pa-3', text: 'Продумать метрики для поиска/рекомендаций', done: false },
          { id: 'ch-pa-4', text: 'Повторить статистику: p-value, доверительный интервал', done: false },
        ],
        tips: [
          'Авито ценит глубокое понимание метрик, не только технические навыки',
          'Готовьтесь к кейсовым вопросам по дизайну экспериментов',
          'Покажите, что вы думаете как владелец продукта, а не только исполнитель',
        ],
      },
    },
  ],

  notifications: [
    {
      id: 'notif-pa-1',
      type: 'recruiter_reply',
      title: 'Ответ от Авито',
      body: 'Авито Технологии: «Дарья, добрый день! Вы подходите нам по опыту...»',
      relatedEntityId: 'thread-pa-1',
      relatedEntityType: 'thread',
      createdAt: daysAgo(1),
      read: false,
    },
    {
      id: 'notif-pa-2',
      type: 'apply_sent',
      title: 'Отклик отправлен',
      body: 'AI отправил отклик в Тинькофф на Product Analyst',
      relatedEntityId: 'app-pa-2',
      relatedEntityType: 'application',
      createdAt: daysAgo(3),
      read: true,
    },
    {
      id: 'notif-pa-3',
      type: 'trial_expiring',
      title: 'Пробный период заканчивается',
      body: 'Осталось 7 дней. Upgrade для продолжения автоматического поиска.',
      createdAt: hoursAgo(12),
      read: false,
    },
  ],

  eventSchedule: [
    {
      id: 'evt-pa-1',
      triggerType: 'timer',
      triggerAfterMs: 15000,
      eventType: 'interview_scheduled',
      payload: {
        interviewId: 'int-pa-1',
        message: 'Авито подтвердили встречу на четверг в 11:00',
      },
      fired: false,
    },
  ],
}
